# Generated by Django 5.1.3 on 2024-11-07 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_department', models.CharField(max_length=100)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_email', models.EmailField(max_length=254, unique=True)),
                ('employee_department', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=20)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.employee')),
                ('role', models.CharField(choices=[('initiator', 'Initiator'), ('hod', 'Head of Department'), ('so', 'Safety Officer')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_code', models.AutoField(primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=100)),
                ('dept_hod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_of_department', to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('incident_type', models.CharField(choices=[('incident', 'Incident'), ('accident', 'Accident')], max_length=20)),
                ('reporter_first_name', models.CharField(max_length=100)),
                ('reporter_last_name', models.CharField(max_length=100)),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('injuries', models.BooleanField(default=False)),
                ('property_damage', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('immediate_actions', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'Closed')], default='initiated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('changes', models.JSONField()),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incidentreport')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_path', models.FileField(upload_to='attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incidentreport')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedPersonnel',
            fields=[
                ('assignment_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_description', models.TextField()),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('hod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('personnel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_personnel', to='api.employee')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incidentreport')),
            ],
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('action_plan_id', models.AutoField(primary_key=True, serialize=False)),
                ('summary', models.TextField()),
                ('tentative_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('safety_officer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incidentreport')),
            ],
        ),
        migrations.CreateModel(
            name='Witness',
            fields=[
                ('witness_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('report_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.incidentreport')),
            ],
        ),
    ]
